# ZebTrack-AI Agent Playbook
- **Product**: Desktop Tkinter app branded DRerio LogAI; Python package `zebtrack`.
- **Runtime**: Python 3.12+, Poetry-managed; launch with `poetry run zebtrack` or `python -m zebtrack`.
- **Docs first**: Validate changes against `docs/ARCHITECTURE.md`, `TRANSITION_NOTE.md`, `docs/REFERENCE_GUIDE.md` before rerouting flows.
- **Config**: Load global settings via `from zebtrack import settings`; precedence `config.yaml` < `config.local.yaml`; Pydantic v2 models enforce `extra="forbid"`.
- **Architecture**: MVVM—`MainViewModel` orchestrates services+UI, `StateManager` tracks observable state, `EventBus` only enabled when `settings.ui_features.enable_event_queue` is true.
- **Lifecycle**: `io/video_source.py` feeds frames → `core/detector_service.DetectorService` wraps plugin detectors (`plugins/`) and zone scaling → `core/processing_worker.ProcessingWorker` handles background analysis → `io/recorder.Recorder` persists Parquet/MP4.
- **UI**: Tk widgets under `zebtrack.ui` never block main thread; schedule updates with `root.after(0, ...)` or via `core/ui_coordinator.UICoordinator`.
- **Wizard**: `ui/wizard/` drives the 5-step project setup through `core/project_workflow_service.ProjectWorkflowService`; respect 1150×550 layout and keep SKIP/IMPORT/PARTIAL/FULL semantics.
- **Project data**: `core/project_manager.ProjectManager` stores ROI templates, arenas, intervals; call `Detector.set_zones()` after getting actual video dimensions to rescale coordinates.
- **Processing modes**: `core/processing_mode.ProcessingMode` toggles multi vs single subject; overlay locks UI when single subject forced—check tests in `tests/test_overlay_integration.py`.
- **Hardware**: Startup runs `utils/hardware_detection.get_hardware_summary()` and `recommend_backend()`; OpenVINO auto-enabled only if `WeightManager` reports converted XML under `openvino_model_cache/`.
- **Logging**: Use `structlog` with `domain.action.result` keys, e.g. `logger.info("controller.load_project.success", project=...)`.
- **Data schema**: Recorder outputs `timestamp, frame, track_id, x1, y1, x2, y2, confidence` with derived centers/cm appended; confirm schema in `tests/test_recorder.py`.
- **Analysis**: `analysis/analysis_service.py` coordinates ROI metrics (`analysis/behavior.py`) and reporting (`analysis/reporter.py`); aggregated outputs saved under `<video>_results/` prefixed `1_`, `2_`, `3_`.
- **Diagnostics**: `MainViewModel.run_model_diagnostic` drives `ui/gui.py`’s `DiagnosticProgressDialog`; keep cancel callbacks responsive via `root.after`.
- **Plugins**: Implement detectors via `plugins/base.py` and register in `plugins/__init__.py`; handle missing `track_id` gracefully for integrations.
- **Testing**: `poetry run pytest -q` for fast suite, `poetry run pytest -m gui -n0` for Tk tests, `poetry run pytest -m slow` when needed; minimum 70% coverage tracked in CI.
- **Scenario coverage**: Consult fixtures in `tests/fixtures/` and flows in `tests/test_wizard_*.py`, `tests/test_interval_frames_config.py`, `test_scenarios/` for realistic data.
- **Lint & Format**: `poetry run ruff check .` (line length 100); use `--fix` carefully.
- **Pre-commit**: `poetry run pre-commit install` then `poetry run pre-commit run --all-files` mirrors CI checks.
- **Scripts**: Tools like `scripts/build_templates.py` and `scripts/compile_translations.py` refresh shared assets; run before release branches.
- **Thread safety**: `StateManager` is thread-safe for cross-thread updates; still pass updates through it instead of mutating view state directly.
- **Common pitfalls**: Forgetting to rescale zones, skipping `root.after`, or writing new columns mid-Parquet breaks downstream analytics—existing tests catch these.
- **When extending**: Prefer augmenting services/adapters (e.g., `ProjectWorkflowService`, `DetectorService`) over bypassing them to keep UI/state synchronization intact.
- **Support**: If unexpected user edits exist, coordinate rather than reverting; log domain events using existing patterns.
