"""Service for applying project settings to video batches.

Extracted from MainViewModel as part of Phase 1 of the refactoring
plan (PLANO_REFATORACAO_MAINVIEWMODEL.md).
Responsible for applying project settings (zones, calibration, etc.)
to newly added batch videos.
"""

import json
import os
from dataclasses import asdict
from pathlib import Path

import structlog

from zebtrack.core.project.project_manager import ProjectManager
from zebtrack.settings import Settings

log = structlog.get_logger()


class BatchConfigurationService:
    """Service for applying project settings to video batches.

    Extracts and centralizes the logic for applying project settings
    (zones, calibration, detector, etc.) to multiple videos in a batch.

    Attributes:
        project_manager: Project manager with access to project data.
        settings: Application settings.
    """

    def __init__(
        self,
        project_manager: ProjectManager,
        settings_obj: Settings,
    ):
        """Initialize the batch configuration service.

        Args:
            project_manager: Project manager instance.
            settings_obj: Application settings.
        """
        self.project_manager = project_manager
        self.settings = settings_obj
        self.log = structlog.get_logger()

    def apply_settings(self, videos: list) -> bool:
        """Apply project settings to a batch of videos.

        For each video in the batch, saves:
        - project_settings.json: Complete project settings
        - zones.json: Zone and ROI data (if configured)

        Args:
            videos: List of dicts with video information (must contain 'path').

        Returns:
            True if settings were applied to all videos successfully,
            False otherwise.
        """
        if not self._validate_project():
            return False

        config = self._build_configuration()
        return self._apply_to_videos(videos, config)

    def _validate_project(self) -> bool:
        """Validate that the project is loaded and configured.

        Returns:
            True if the project is valid, False otherwise.
        """
        if not self.project_manager.project_path:
            self.log.warning("batch_config.no_project_path")
            return False
        return True

    def _build_configuration(self) -> dict:
        """Build a configuration dict from project data.

        Returns:
            Dict containing all necessary settings:
            - zone_data: Zone and ROI data
            - calibration: Calibration data
            - project_data: Complete project data
            - has_zones: Flag indicating whether zones are configured
            - has_calibration: Flag indicating whether calibration exists
            - has_rois: Number of configured ROIs
        """
        project_data = self.project_manager.project_data
        zone_data = self.project_manager.get_zone_data()
        calibration = project_data.get("calibration", {})

        self.log.info(
            "batch_config.build_configuration",
            has_zones=bool(zone_data and zone_data.polygon),
            has_calibration=bool(calibration),
            has_rois=len(zone_data.roi_polygons) if zone_data else 0,
        )

        return {
            "zone_data": zone_data,
            "calibration": calibration,
            "project_data": project_data,
            "has_zones": bool(zone_data and zone_data.polygon),
            "has_calibration": bool(calibration),
            "has_rois": len(zone_data.roi_polygons) if zone_data else 0,
        }

    def _apply_to_videos(self, videos: list, config: dict) -> bool:
        """Apply configuration to each video in the batch.

        Args:
            videos: List of dicts with video information.
            config: Configuration dict generated by _build_configuration.

        Returns:
            True if settings were applied to all videos,
            False otherwise.
        """
        self.log.info(
            "batch_config.apply_to_videos",
            videos_count=len(videos),
            has_zones=config["has_zones"],
            has_calibration=config["has_calibration"],
            has_rois=config["has_rois"],
        )

        settings_applied = 0
        for video_info in videos:
            if self._apply_to_single_video(video_info, config):
                settings_applied += 1

        self.log.info(
            "batch_config.settings_applied",
            total_videos=len(videos),
            successful=settings_applied,
        )

        return settings_applied == len(videos)

    def _apply_to_single_video(self, video_info: dict, config: dict) -> bool:
        """Apply configuration to a single video.

        Args:
            video_info: Dict with video information (must contain 'path').
            config: Configuration dict.

        Returns:
            True if settings were applied successfully, False otherwise.
        """
        video_path = video_info.get("path")
        if not video_path:
            return False

        experiment_id = os.path.splitext(os.path.basename(video_path))[0]
        results_path = self.project_manager.resolve_results_directory(
            experiment_id,
            video_path=video_path,
        )

        try:
            self._prepare_results_directory(results_path)
            self._save_project_settings(results_path, video_info, config)
            self._save_zone_data(results_path, experiment_id, config)
            return True

        # except Exception justified: batch configuration validation — heterogeneous data sources
        except Exception as e:
            self.log.error(
                "batch_config.settings_save_error",
                video=experiment_id,
                error=str(e),
            )
            return False

    def _prepare_results_directory(self, results_path: Path) -> None:
        """Prepare the results directory for the video.

        Args:
            results_path: Path to the results directory.
        """
        results_path.mkdir(parents=True, exist_ok=True)

    def _save_project_settings(self, results_path: Path, video_info: dict, config: dict) -> None:
        """Save project settings as JSON.

        Args:
            results_path: Path to the results directory.
            video_info: Dict with video information.
            config: Configuration dict.
        """
        project_data = config["project_data"]
        settings_file = results_path / "project_settings.json"

        settings_data = {
            "project_name": self.project_manager.get_project_name(),
            "active_weight": project_data.get("active_weight"),
            "use_openvino": project_data.get("use_openvino", False),
            "calibration": config["calibration"],
            "video_settings": video_info,
            "timestamp": project_data.get("timestamp"),
            "analysis_interval_frames": project_data.get("analysis_interval_frames", 10),
            "display_interval_frames": project_data.get("display_interval_frames", 10),
            "detector_config": self.project_manager.get_detector_state(),
        }

        with open(settings_file, "w") as f:
            json.dump(settings_data, f, indent=2)

    def _save_zone_data(self, results_path: Path, experiment_id: str, config: dict) -> None:
        """Save zone data as JSON (if present).

        Args:
            results_path: Path to the results directory.
            experiment_id: Experiment/video ID.
            config: Configuration dict.
        """
        zone_data = config["zone_data"]

        if zone_data and (zone_data.polygon or zone_data.roi_polygons):
            zones_file = results_path / "zones.json"

            with open(zones_file, "w") as f:
                json.dump(asdict(zone_data), f, indent=2)

            self.log.info(
                "batch_config.zones_saved",
                video=experiment_id,
                zones_file=str(zones_file),
                settings_file=str(results_path / "project_settings.json"),
            )
